# ===============================
#     General Configuration
# ===============================

enderchest:
  drop-on-death: true # Whether to drop the enderchest on death
  drop-on-pvp: false  # Whether to drop the enderchest only if the killer was a player.

tracker:
  max-distance: 500 # The max distance the compass should work.
  update-interval: 1 # The interval in seconds to update the compass.

ancient-debris:
  enabled: true
  minimum-scrap: 1
  maximum-scrap: 3

double-gaps: true # Whether to allow double gaps crafting.

extended-t2-strength: false