name: ArtualCore
version: '2.2.3'
main: org.TheoCodes.ArtualSMP.Plugin.artual.Artual
api-version: '1.19'
authors: [ prodtheo, Harfull, ChatGPT ]
description: Private plugin powering ArtualCM's SMP.

commands:
  gold:
    description: (DEV) Test the functionality of the plugin.
    usage: /test
  getcompass:
    description: (DEV) Get the player tracker for testing.
    usage: /getcompass
  reloadconfig:
    description: (DEV) Reload the configuration of the plugin.
    usage: /reloadconfig
    permission: artual.reload
  chunk:
    description: (PLAYER) Use the chunk claiming tools.
    usage: /chunk <claim|delete|list|info>


permissions:
  artual.reload:
    description: Lets the user with the permission reload the config.yml
    default: op
